---
- name: Install and Setup Image Builder on-prem
  hosts: "{{ survey_hostname }}"
  gather_facts: true

  vars:
    my_tmp_file: /tmp/tmpfile.toml
    my_toml_file:
      - baseos.toml.j2
      - satellite.toml.j2

  vars_files:
    - vars/baseos_user.yml

  tasks:
    - name: Fail the playbook if the host OS is not currently RHEL7 or RHEL8
      ansible.builtin.fail:
        msg: "The host {{ ansible_hostname }} is RHEL{{ ansible_distribution_major_version }} and is not supported for Image Builder "
      when: 
        - ansible_facts['distribution_major_version'] != "8"
        - ansible_facts['distribution_major_version'] != "9"

    - name: Create weldr group
      ansible.builtin.group:
        name: weldr
        state: present

    - name: Add baseos user to weldr group
      ansible.builtin.user:
        name: "{{ baseos_name }}"
        groups: weldr
        append: true

    - name: Install packages needed for Image Builder server
      ansible.builtin.dnf:
        name: 
          - osbuild-composer
          - composer-cli
          - cockpit-composer
          - openscap-scanner
          - scap-security-guide
        state: latest
    
    - name: Enable auto-complete
      ansible.builtin.shell: "source /etc/bash_completion.d/composer-cli"
      changed_when: false

    - name: Create repo directory for using Satellite CV as content source
      ansible.builtin.file:
        path: /etc/osbuild-composer/repositories
        state: directory
        mode: '0755'
        owner: root 
        group: root

    - name: Copy the hard-coded repos 
      ansible.builtin.copy:
        src: /usr/share/osbuild-composer/repositories/rhel-{{ ansible_distribution_version }}.json
        dest: /etc/osbuild-composer/repositories
        remote_src: true   

    - name: Get YourEnv and YourCV 
      ansible.builtin.shell: "subscription-manager identity | grep 'environment name:' | awk '{print $3}'"
      register: sub_identity
      changed_when: false

    - name: Set fact with YourEnv and YourCV
      ansible.builtin.set_fact:
        my_var: "{{ sub_identity.stdout }}"

    - name: Replace cdn.redhat.com with satellite server
      ansible.builtin.shell: "sed -i -e 's|cdn.redhat.com|{{ survey_sat_svr }}/pulp/content/{{ sat_org }}/{{ my_var }}|' /etc/osbuild-composer/repositories/*.json"
      changed_when: false

    - name: "Replace {{ ansible_distribution_version }} with {{ ansible_distribution_major_version }} in rhel-{{ ansible_distribution_version }}.json"
      ansible.builtin.shell: "sed -i -e 's|{{ ansible_distribution_version }}|{{ ansible_distribution_major_version }}|' /etc/osbuild-composer/repositories/rhel-{{ ansible_distribution_version }}.json"
      changed_when: false

    - name: Enable and start image builder socket
      ansible.builtin.systemd:
        name: osbuild-composer.socket
        state: started
        enabled: true

    - name: Enable and start web console
      ansible.builtin.systemd:
        name: cockpit.socket
        state: started
        enabled: true

    - name: Process multiple blueprint files
      include_tasks: "image_bldr_task.yml"
      loop: "{{ my_toml_file }}"