---
- name: Perform Leapp upgrade on rhel host
  hosts: "{{ survey_hostname }}"

  vars_files:
    - vars/rhel{{ ansible_distribution_major_version }}_leapp_vars.yml

  tasks:
    - name: Fail the playbook if the host OS is not currently RHEL7 or RHEL8
      ansible.builtin.fail:
        msg: "The host {{ ansible_hostname }} is RHEL{{ ansible_distribution_major_version }}. No LEAPP for you!"
      when: 
        - ansible_facts['distribution_major_version'] != "7"
        - ansible_facts['distribution_major_version'] != "8"

    - name: Register the host with the proper LEAPP Activation Key
      ansible.builtin.command: "subscription-manager register --org={{ sat_org }} --activationkey={{ leapp_ak }} --force"

    - name: Ensure Leapp is installed
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ inst_pkgs }}"

    - name: Include Leapp{{ ansible_distribution_major_version }} Inhibitor
      ansible.builtin.include_tasks: "tasks/leapp{{ ansible_distribution_major_version  }}_inhibitor_task.yml"

    - name: Run the leapp preupgrade
      ansible.builtin.command: leapp preupgrade
      changed_when: false
      register: preupgrade_result

    - name: Run the leapp upgrade
      ansible.builtin.command: leapp upgrade
      register: upgrade_result

    - name: Reboot the server to complete the upgrade
      ansible.builtin.reboot: