---
- name: Register host to satellite 
  hosts: rhel79.ofam.dev
  become: yes
  vars_files:
    - vars/sat_register_vars.yml

  tasks:
    - name: Register the host to satellite with the correct AK
      ansible.builtin.shell: "{{ RHEL7_AK }}"  
