---
- name: Upgrade RHEL Servers
  hosts: rhel79.ofam.dev
  become: yes

  tasks:
    - name: Update the OS with latest patches
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Check if host needs rebooting
      ansible.builtin.command: needs-restarting -r
      register: reboot_result
      changed_when: false

    - name: Reboot the server to complete the upgrade
      ansible.builtin.reboot:
      when: "'Reboot is required' in reboot_result.stdout"
