---
- name: Add Toml file used for blueprint to tmp dir
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ my_tmp_file }}"

- name: Create blueprint
  ansible.builtin.command: "composer-cli blueprints push {{ my_tmp_file }}"
  changed_when: false

- name: Remove the blueprint Toml tmp file
  ansible.builtin.file:
    path: "{{ my_tmp_file }}"
    state: absent