---
- name: Modify leapp file to avoid inhibitor
  ansible.builtin.lineinfile:
    path: /etc/leapp/files/device_driver_deprecation_data.json
    search_string: '"device_id": "x86_64:intel:6:[168-255]",'
    line: '      "device_id": "x86_64:intel:6:[190-255]",'
    state: present
    backup: true

- name: Disable ssh root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    line: '#PermitRootLogin yes'

- name: Disable AllowZoneDrifting
  ansible.builtin.lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=yes'
    line: 'AllowZoneDrifting=no'